### ISSUE TITLE
请问你什么怎么把图片打上标签的呢？

### ISSUE THREAD

**Issue by NeXT1995** [mrlittlepig/ImageProcessing#1]
因为你是直接读取图片和标签的？那你的标签改如何做？因为我是想通过训练一些相似或相近的图片来识别图片中特征地物的

**Comment by mrlittlepig** [comment]
你说的打标签是给自己的图片数据打上label？这个需要自己标注数据，mnist数据集已经是标注过的数据，label文件存放到二进制文件里面了，可以调用函数来读取label

**Comment by zhaopanpan73** [comment]
我觉得训练的时候还是用的tensorflow本身自带的mnist数据集，并没有换成我自己的图片，忧伤

**Comment by WenmuZhou** [comment]
Please use the tensorflow latest api `tf.data.dataset` to read the data.
If it is a classification task
All you need to do is store the data as follows:
```
path/0/0_0.jpg
path/0/0_1.jpg
path/0/0_2.jpg
path/1/1_0.jpg
path/1/1_1.jpg
......
path/n/n_0.jpg
```

**Comment by WenmuZhou** [comment]
I will close this issues, if you have others question about how to read the data, you can reopen it
