### ISSUE TITLE
关于用TFrecord训练的问题

### ISSUE THREAD

**Issue by Jacky-Luo** [mrlittlepig/ImageProcessing#2]
我尝试使用文件里面的TFrecords来训练，感觉数据是对的，但是训练的loss一直是NAN，不知道您是否也是这样？谢谢~

**Comment by mrlittlepig** [comment]
我之前也试过，我这个TFrecords是有点问题，TRrecords推荐使用https://github.com/WenmuZhou/PythonDeepLearning/tree/master/tensorflow_project

**Comment by mrlittlepig** [comment]
现在跟目录下的classifier是tfrecords训练脚本，在运行的时候会调用lenet网络结构，在net文件夹下面存放的是网络结构文件
