### ISSUE TITLE
请问txt文件需要自己的生成吗

### ISSUE THREAD

**Issue by wjy619251334** [mrlittlepig/ImageProcessing#4]
现在有每个文件夹的MNIST 的bmp格式的图片~
需要把每个文件夹内图片标题和对应标签生成txt的每一行文件再运行吗？
请问生成txt文件的格式有什么要求吗？
还需要修改别的py文件吗？

**Comment by WenmuZhou** [comment]
txt文件格式如下
path label

**Comment by wjy619251334** [comment]
是每一个图片占一行吗？
读取的时候出现了错误

**Comment by WenmuZhou** [comment]
每一个图片和对应的标签占一行
