### ISSUE TITLE
请问有保存训练结果和用训练结果来预测图片的类吗？

### ISSUE THREAD

**Issue by tomoya92** [mrlittlepig/ImageProcessing#5]
你好，我又来了

训练是训练好了，然后看到在根目录下有个 data 的目录，用tensorboard可以看一些信息，然后看到里面不止有log，还有 model.ckpt.xxx 的文件，这不就是sess.save() 保存的模型文件吗？

但问题是

1. 我在classifier.py 跟 net/lenet.py 里没有找到 tf.Session() ，请问大大是怎么生成的这些 ckpt 的文件的呢？
2. 能否请大大添加上一个预测的文件，输入图片，调用训练好的模型来预测结果是啥（也可以提供一下思路）

谢谢了 : ）

**Comment by mrlittlepig** [comment]
在classifier.py里面有调用estmator的evaluate操作，这个操作就是调用生成的ckpt文件对测试集进行测试，暂时可以用这个来，预测单张图片的接口我还没有实现，在12月份我会抽空完成python端的预测，也欢迎大家提交pull request来完善这个工作

**Comment by tomoya92** [comment]
好的，谢谢，我要是弄出来了，会提pr的

**Comment by mrlittlepig** [comment]
现在根目录下的evaluation.py 是调用训练好的模型来预测的脚本，具体可以在代码里面设置调用的网络结构和模型等参数

**Comment by tomoya92** [comment]
感谢，我想写一个来着，但restore的时候，还要加载模型，然后就弄不好了，结果还是大大分享了

再次感谢 😄
